name: Build Godot for Windows and macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, mac]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: obees
          preset: ${{ matrix.platform }}
          debugMode: "true"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obees-${{ matrix.platform }}
          path: ${{ steps.build.outputs.build }}
