name: Build Godot for Windows and macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.4.1
        use-mono: false

    - name: Export for macOS
      run: |
        godot --headless --export-release "macOS" build/game.app

    - name: Upload exported builds
      uses: actions/upload-artifact@v4
      with:
        name: godot-builds
        path: build/
